---
# Configure & start the deploy server subsystem
- name: playbook exists
  file: path={{ deployer_playbook }}
        state=file
  when: lookup('env', 'DISABLE_PLAYBOOK_CHECK') == ''

- include: ansible.yml

- name: deployer upstart config exists
  template: dest=/etc/init/deployer.conf
            src=deployer.conf
            mode=0644
            owner=root

- name: reload initctl conf
  command: /sbin/initctl reload-configuration

- name: stop deployer service
  service: name=deployer state=stopped

- name: sync deployer binary
  copy: dest={{ deployer_bin }}
        src=deployer.linux
        mode=0755
        owner=root

- name: start deployer service
  service: name=deployer state=started
